version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/lumine/web"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps(npm)"
    labels:
      - "dependencies"
    security-updates: true
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps(go)"
    labels:
      - "dependencies"
    security-updates: true
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps(actions)"
    labels:
      - "dependencies"
    security-updates: true
