version: "3.8"

services:
  ayato:
    build:
      context: ./ayato
      dockerfile: Dockerfile
    ports:
      - "9090:8080"
    environment:
      AYATO_STORE_SQL_DRIVER: ${AYATO_STORE_SQL_DRIVER}
      AYATO_STORE_SQL_HOST: ${AYATO_STORE_SQL_HOST}
      AYATO_STORE_SQL_PORT: ${AYATO_STORE_SQL_PORT}
      AYATO_STORE_SQL_USER: ${AYATO_STORE_SQL_USER}
      AYATO_STORE_SQL_PASSWORD: ${AYATO_STORE_SQL_PASSWORD}
      AYATO_STORE_SQL_DATABASE: ${AYATO_STORE_SQL_DATABASE}
      AYATO_STORE_SQL_ADDITIONALDSN: ${AYATO_STORE_SQL_ADDITIONALDSN}
      AYATO_STORE_DBTYPE: ${AYATO_STORE_DBTYPE}
      AYATO_STORE_AWSS3_REGION: ${AYATO_STORE_AWSS3_REGION}
      AYATO_STORE_AWSS3_BUCKET: ${AYATO_STORE_AWSS3_BUCKET}
      AYATO_STORE_AWSS3_ACCESSKEYID: ${AYATO_STORE_AWSS3_ACCESSKEYID}
      AYATO_STORE_AWSS3_SECRETKEY: ${AYATO_STORE_AWSS3_SECRETKEY}
      AYATO_STORE_AWSS3_ENDPOINT: ${AYATO_STORE_AWSS3_ENDPOINT}
    volumes:
      - ./ayato:/app
    env_file:
      - ./ayato/.env
