// Code generated by MockGen. DO NOT EDIT.
// Source: blob.go
//
// Generated by this command:
//
//	mockgen -source=blob.go -destination=../test/mocks/blob.go -package=mocks -mock_names Store=MockBlobStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	stream "github.com/Hayao0819/Kamisato/ayato/stream"
	gomock "go.uber.org/mock/gomock"
)

// MockBlobStore is a mock of Store interface.
type MockBlobStore struct {
	ctrl     *gomock.Controller
	recorder *MockBlobStoreMockRecorder
	isgomock struct{}
}

// MockBlobStoreMockRecorder is the mock recorder for MockBlobStore.
type MockBlobStoreMockRecorder struct {
	mock *MockBlobStore
}

// NewMockBlobStore creates a new mock instance.
func NewMockBlobStore(ctrl *gomock.Controller) *MockBlobStore {
	mock := &MockBlobStore{ctrl: ctrl}
	mock.recorder = &MockBlobStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlobStore) EXPECT() *MockBlobStoreMockRecorder {
	return m.recorder
}

// Arches mocks base method.
func (m *MockBlobStore) Arches(repo string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Arches", repo)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Arches indicates an expected call of Arches.
func (mr *MockBlobStoreMockRecorder) Arches(repo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Arches", reflect.TypeOf((*MockBlobStore)(nil).Arches), repo)
}

// DeleteFile mocks base method.
func (m *MockBlobStore) DeleteFile(repo, arch, file string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFile", repo, arch, file)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFile indicates an expected call of DeleteFile.
func (mr *MockBlobStoreMockRecorder) DeleteFile(repo, arch, file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFile", reflect.TypeOf((*MockBlobStore)(nil).DeleteFile), repo, arch, file)
}

// FetchFile mocks base method.
func (m *MockBlobStore) FetchFile(repo, arch, file string) (stream.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchFile", repo, arch, file)
	ret0, _ := ret[0].(stream.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchFile indicates an expected call of FetchFile.
func (mr *MockBlobStoreMockRecorder) FetchFile(repo, arch, file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchFile", reflect.TypeOf((*MockBlobStore)(nil).FetchFile), repo, arch, file)
}

// Files mocks base method.
func (m *MockBlobStore) Files(repo, arch string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Files", repo, arch)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Files indicates an expected call of Files.
func (mr *MockBlobStoreMockRecorder) Files(repo, arch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Files", reflect.TypeOf((*MockBlobStore)(nil).Files), repo, arch)
}

// RepoNames mocks base method.
func (m *MockBlobStore) RepoNames() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RepoNames")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RepoNames indicates an expected call of RepoNames.
func (mr *MockBlobStoreMockRecorder) RepoNames() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RepoNames", reflect.TypeOf((*MockBlobStore)(nil).RepoNames))
}

// StoreFile mocks base method.
func (m *MockBlobStore) StoreFile(repo, arch string, file stream.SeekFile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreFile", repo, arch, file)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreFile indicates an expected call of StoreFile.
func (mr *MockBlobStoreMockRecorder) StoreFile(repo, arch, file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreFile", reflect.TypeOf((*MockBlobStore)(nil).StoreFile), repo, arch, file)
}

// StoreFileWithSignedURL mocks base method.
func (m *MockBlobStore) StoreFileWithSignedURL(repo, arch, name string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreFileWithSignedURL", repo, arch, name)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StoreFileWithSignedURL indicates an expected call of StoreFileWithSignedURL.
func (mr *MockBlobStoreMockRecorder) StoreFileWithSignedURL(repo, arch, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreFileWithSignedURL", reflect.TypeOf((*MockBlobStore)(nil).StoreFileWithSignedURL), repo, arch, name)
}
