// Code generated by MockGen. DO NOT EDIT.
// Source: blob.go
//
// Generated by this command:
//
//	mockgen -source=blob.go -destination=../../test/mocks/blob.go -package=mocks -mock_names Store=MockBlobStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	blob "github.com/Hayao0819/Kamisato/ayato/repository/blob"
	stream "github.com/Hayao0819/Kamisato/ayato/stream"
	gomock "go.uber.org/mock/gomock"
)

// MockOrphanDeleter is a mock of OrphanDeleter interface.
type MockOrphanDeleter struct {
	ctrl     *gomock.Controller
	recorder *MockOrphanDeleterMockRecorder
	isgomock struct{}
}

// MockOrphanDeleterMockRecorder is the mock recorder for MockOrphanDeleter.
type MockOrphanDeleterMockRecorder struct {
	mock *MockOrphanDeleter
}

// NewMockOrphanDeleter creates a new mock instance.
func NewMockOrphanDeleter(ctrl *gomock.Controller) *MockOrphanDeleter {
	mock := &MockOrphanDeleter{ctrl: ctrl}
	mock.recorder = &MockOrphanDeleterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrphanDeleter) EXPECT() *MockOrphanDeleterMockRecorder {
	return m.recorder
}

// DeleteFileIfUnchanged mocks base method.
func (m *MockOrphanDeleter) DeleteFileIfUnchanged(repo, arch string, expected blob.FileInfo, cutoff time.Time) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFileIfUnchanged", repo, arch, expected, cutoff)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteFileIfUnchanged indicates an expected call of DeleteFileIfUnchanged.
func (mr *MockOrphanDeleterMockRecorder) DeleteFileIfUnchanged(repo, arch, expected, cutoff any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFileIfUnchanged", reflect.TypeOf((*MockOrphanDeleter)(nil).DeleteFileIfUnchanged), repo, arch, expected, cutoff)
}

// MockPublicationLocker is a mock of PublicationLocker interface.
type MockPublicationLocker struct {
	ctrl     *gomock.Controller
	recorder *MockPublicationLockerMockRecorder
	isgomock struct{}
}

// MockPublicationLockerMockRecorder is the mock recorder for MockPublicationLocker.
type MockPublicationLockerMockRecorder struct {
	mock *MockPublicationLocker
}

// NewMockPublicationLocker creates a new mock instance.
func NewMockPublicationLocker(ctrl *gomock.Controller) *MockPublicationLocker {
	mock := &MockPublicationLocker{ctrl: ctrl}
	mock.recorder = &MockPublicationLockerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublicationLocker) EXPECT() *MockPublicationLockerMockRecorder {
	return m.recorder
}

// LockPublication mocks base method.
func (m *MockPublicationLocker) LockPublication(repo string) (func(), error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockPublication", repo)
	ret0, _ := ret[0].(func())
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LockPublication indicates an expected call of LockPublication.
func (mr *MockPublicationLockerMockRecorder) LockPublication(repo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockPublication", reflect.TypeOf((*MockPublicationLocker)(nil).LockPublication), repo)
}

// MockMetaFetcher is a mock of MetaFetcher interface.
type MockMetaFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockMetaFetcherMockRecorder
	isgomock struct{}
}

// MockMetaFetcherMockRecorder is the mock recorder for MockMetaFetcher.
type MockMetaFetcherMockRecorder struct {
	mock *MockMetaFetcher
}

// NewMockMetaFetcher creates a new mock instance.
func NewMockMetaFetcher(ctrl *gomock.Controller) *MockMetaFetcher {
	mock := &MockMetaFetcher{ctrl: ctrl}
	mock.recorder = &MockMetaFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetaFetcher) EXPECT() *MockMetaFetcherMockRecorder {
	return m.recorder
}

// FetchFileWithMeta mocks base method.
func (m *MockMetaFetcher) FetchFileWithMeta(repo, arch, file string) (stream.File, blob.FileMeta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchFileWithMeta", repo, arch, file)
	ret0, _ := ret[0].(stream.File)
	ret1, _ := ret[1].(blob.FileMeta)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FetchFileWithMeta indicates an expected call of FetchFileWithMeta.
func (mr *MockMetaFetcherMockRecorder) FetchFileWithMeta(repo, arch, file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchFileWithMeta", reflect.TypeOf((*MockMetaFetcher)(nil).FetchFileWithMeta), repo, arch, file)
}

// MockObjectMover is a mock of ObjectMover interface.
type MockObjectMover struct {
	ctrl     *gomock.Controller
	recorder *MockObjectMoverMockRecorder
	isgomock struct{}
}

// MockObjectMoverMockRecorder is the mock recorder for MockObjectMover.
type MockObjectMoverMockRecorder struct {
	mock *MockObjectMover
}

// NewMockObjectMover creates a new mock instance.
func NewMockObjectMover(ctrl *gomock.Controller) *MockObjectMover {
	mock := &MockObjectMover{ctrl: ctrl}
	mock.recorder = &MockObjectMoverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObjectMover) EXPECT() *MockObjectMoverMockRecorder {
	return m.recorder
}

// CopyObject mocks base method.
func (m *MockObjectMover) CopyObject(srcKey, dstKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopyObject", srcKey, dstKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// CopyObject indicates an expected call of CopyObject.
func (mr *MockObjectMoverMockRecorder) CopyObject(srcKey, dstKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopyObject", reflect.TypeOf((*MockObjectMover)(nil).CopyObject), srcKey, dstKey)
}

// DeleteObject mocks base method.
func (m *MockObjectMover) DeleteObject(objKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObject", objKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteObject indicates an expected call of DeleteObject.
func (mr *MockObjectMoverMockRecorder) DeleteObject(objKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObject", reflect.TypeOf((*MockObjectMover)(nil).DeleteObject), objKey)
}

// ListObjects mocks base method.
func (m *MockObjectMover) ListObjects(prefix string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListObjects", prefix)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListObjects indicates an expected call of ListObjects.
func (mr *MockObjectMoverMockRecorder) ListObjects(prefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListObjects", reflect.TypeOf((*MockObjectMover)(nil).ListObjects), prefix)
}

// MockBlobStore is a mock of Store interface.
type MockBlobStore struct {
	ctrl     *gomock.Controller
	recorder *MockBlobStoreMockRecorder
	isgomock struct{}
}

// MockBlobStoreMockRecorder is the mock recorder for MockBlobStore.
type MockBlobStoreMockRecorder struct {
	mock *MockBlobStore
}

// NewMockBlobStore creates a new mock instance.
func NewMockBlobStore(ctrl *gomock.Controller) *MockBlobStore {
	mock := &MockBlobStore{ctrl: ctrl}
	mock.recorder = &MockBlobStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlobStore) EXPECT() *MockBlobStoreMockRecorder {
	return m.recorder
}

// Arches mocks base method.
func (m *MockBlobStore) Arches(repo string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Arches", repo)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Arches indicates an expected call of Arches.
func (mr *MockBlobStoreMockRecorder) Arches(repo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Arches", reflect.TypeOf((*MockBlobStore)(nil).Arches), repo)
}

// DeleteFile mocks base method.
func (m *MockBlobStore) DeleteFile(repo, arch, file string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFile", repo, arch, file)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFile indicates an expected call of DeleteFile.
func (mr *MockBlobStoreMockRecorder) DeleteFile(repo, arch, file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFile", reflect.TypeOf((*MockBlobStore)(nil).DeleteFile), repo, arch, file)
}

// FetchFile mocks base method.
func (m *MockBlobStore) FetchFile(repo, arch, file string) (stream.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchFile", repo, arch, file)
	ret0, _ := ret[0].(stream.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchFile indicates an expected call of FetchFile.
func (mr *MockBlobStoreMockRecorder) FetchFile(repo, arch, file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchFile", reflect.TypeOf((*MockBlobStore)(nil).FetchFile), repo, arch, file)
}

// FetchFileWithETag mocks base method.
func (m *MockBlobStore) FetchFileWithETag(repo, arch, file string) (stream.File, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchFileWithETag", repo, arch, file)
	ret0, _ := ret[0].(stream.File)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FetchFileWithETag indicates an expected call of FetchFileWithETag.
func (mr *MockBlobStoreMockRecorder) FetchFileWithETag(repo, arch, file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchFileWithETag", reflect.TypeOf((*MockBlobStore)(nil).FetchFileWithETag), repo, arch, file)
}

// Files mocks base method.
func (m *MockBlobStore) Files(repo, arch string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Files", repo, arch)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Files indicates an expected call of Files.
func (mr *MockBlobStoreMockRecorder) Files(repo, arch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Files", reflect.TypeOf((*MockBlobStore)(nil).Files), repo, arch)
}

// FilesWithMeta mocks base method.
func (m *MockBlobStore) FilesWithMeta(repo, arch string) ([]blob.FileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilesWithMeta", repo, arch)
	ret0, _ := ret[0].([]blob.FileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilesWithMeta indicates an expected call of FilesWithMeta.
func (mr *MockBlobStoreMockRecorder) FilesWithMeta(repo, arch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilesWithMeta", reflect.TypeOf((*MockBlobStore)(nil).FilesWithMeta), repo, arch)
}

// RepoNames mocks base method.
func (m *MockBlobStore) RepoNames() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RepoNames")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RepoNames indicates an expected call of RepoNames.
func (mr *MockBlobStoreMockRecorder) RepoNames() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RepoNames", reflect.TypeOf((*MockBlobStore)(nil).RepoNames))
}

// StoreFile mocks base method.
func (m *MockBlobStore) StoreFile(repo, arch string, file stream.SeekFile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreFile", repo, arch, file)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreFile indicates an expected call of StoreFile.
func (mr *MockBlobStoreMockRecorder) StoreFile(repo, arch, file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreFile", reflect.TypeOf((*MockBlobStore)(nil).StoreFile), repo, arch, file)
}

// StoreFileIfMatch mocks base method.
func (m *MockBlobStore) StoreFileIfMatch(repo, arch string, file stream.SeekFile, etag string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreFileIfMatch", repo, arch, file, etag)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreFileIfMatch indicates an expected call of StoreFileIfMatch.
func (mr *MockBlobStoreMockRecorder) StoreFileIfMatch(repo, arch, file, etag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreFileIfMatch", reflect.TypeOf((*MockBlobStore)(nil).StoreFileIfMatch), repo, arch, file, etag)
}

// StoreFileWithSignedURL mocks base method.
func (m *MockBlobStore) StoreFileWithSignedURL(repo, arch, name string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreFileWithSignedURL", repo, arch, name)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StoreFileWithSignedURL indicates an expected call of StoreFileWithSignedURL.
func (mr *MockBlobStoreMockRecorder) StoreFileWithSignedURL(repo, arch, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreFileWithSignedURL", reflect.TypeOf((*MockBlobStore)(nil).StoreFileWithSignedURL), repo, arch, name)
}
