// Code generated by MockGen. DO NOT EDIT.
// Source: namestore.go
//
// Generated by this command:
//
//	mockgen -source=namestore.go -destination=../test/mocks/namestore.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockNameStore is a mock of NameStore interface.
type MockNameStore struct {
	ctrl     *gomock.Controller
	recorder *MockNameStoreMockRecorder
	isgomock struct{}
}

// MockNameStoreMockRecorder is the mock recorder for MockNameStore.
type MockNameStoreMockRecorder struct {
	mock *MockNameStore
}

// NewMockNameStore creates a new mock instance.
func NewMockNameStore(ctrl *gomock.Controller) *MockNameStore {
	mock := &MockNameStore{ctrl: ctrl}
	mock.recorder = &MockNameStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNameStore) EXPECT() *MockNameStoreMockRecorder {
	return m.recorder
}

// DeletePackageFileEntry mocks base method.
func (m *MockNameStore) DeletePackageFileEntry(arch, packageName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePackageFileEntry", arch, packageName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePackageFileEntry indicates an expected call of DeletePackageFileEntry.
func (mr *MockNameStoreMockRecorder) DeletePackageFileEntry(arch, packageName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePackageFileEntry", reflect.TypeOf((*MockNameStore)(nil).DeletePackageFileEntry), arch, packageName)
}

// PackageFile mocks base method.
func (m *MockNameStore) PackageFile(arch, name string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PackageFile", arch, name)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PackageFile indicates an expected call of PackageFile.
func (mr *MockNameStoreMockRecorder) PackageFile(arch, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PackageFile", reflect.TypeOf((*MockNameStore)(nil).PackageFile), arch, name)
}

// StorePackageFile mocks base method.
func (m *MockNameStore) StorePackageFile(arch, packageName, filePath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StorePackageFile", arch, packageName, filePath)
	ret0, _ := ret[0].(error)
	return ret0
}

// StorePackageFile indicates an expected call of StorePackageFile.
func (mr *MockNameStoreMockRecorder) StorePackageFile(arch, packageName, filePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StorePackageFile", reflect.TypeOf((*MockNameStore)(nil).StorePackageFile), arch, packageName, filePath)
}
