// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=../test/mocks/repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	stream "github.com/Hayao0819/Kamisato/ayato/stream"
	repo "github.com/Hayao0819/Kamisato/pkg/pacman/repo"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// Arches mocks base method.
func (m *MockStore) Arches(arg0 string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Arches", arg0)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Arches indicates an expected call of Arches.
func (mr *MockStoreMockRecorder) Arches(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Arches", reflect.TypeOf((*MockStore)(nil).Arches), arg0)
}

// DeleteFile mocks base method.
func (m *MockStore) DeleteFile(arg0, arch, file string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFile", arg0, arch, file)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFile indicates an expected call of DeleteFile.
func (mr *MockStoreMockRecorder) DeleteFile(arg0, arch, file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFile", reflect.TypeOf((*MockStore)(nil).DeleteFile), arg0, arch, file)
}

// FetchFile mocks base method.
func (m *MockStore) FetchFile(arg0, arch, file string) (stream.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchFile", arg0, arch, file)
	ret0, _ := ret[0].(stream.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchFile indicates an expected call of FetchFile.
func (mr *MockStoreMockRecorder) FetchFile(arg0, arch, file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchFile", reflect.TypeOf((*MockStore)(nil).FetchFile), arg0, arch, file)
}

// Files mocks base method.
func (m *MockStore) Files(arg0, arch string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Files", arg0, arch)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Files indicates an expected call of Files.
func (mr *MockStoreMockRecorder) Files(arg0, arch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Files", reflect.TypeOf((*MockStore)(nil).Files), arg0, arch)
}

// InitArch mocks base method.
func (m *MockStore) InitArch(name, arch string, useSignedDB bool, gnupgDir *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitArch", name, arch, useSignedDB, gnupgDir)
	ret0, _ := ret[0].(error)
	return ret0
}

// InitArch indicates an expected call of InitArch.
func (mr *MockStoreMockRecorder) InitArch(name, arch, useSignedDB, gnupgDir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitArch", reflect.TypeOf((*MockStore)(nil).InitArch), name, arch, useSignedDB, gnupgDir)
}

// RepoAdd mocks base method.
func (m *MockStore) RepoAdd(name, arch string, pkg, sig stream.SeekFile, useSignedDB bool, gnupgDir *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RepoAdd", name, arch, pkg, sig, useSignedDB, gnupgDir)
	ret0, _ := ret[0].(error)
	return ret0
}

// RepoAdd indicates an expected call of RepoAdd.
func (mr *MockStoreMockRecorder) RepoAdd(name, arch, pkg, sig, useSignedDB, gnupgDir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RepoAdd", reflect.TypeOf((*MockStore)(nil).RepoAdd), name, arch, pkg, sig, useSignedDB, gnupgDir)
}

// RepoNames mocks base method.
func (m *MockStore) RepoNames() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RepoNames")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RepoNames indicates an expected call of RepoNames.
func (mr *MockStoreMockRecorder) RepoNames() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RepoNames", reflect.TypeOf((*MockStore)(nil).RepoNames))
}

// RepoRemove mocks base method.
func (m *MockStore) RepoRemove(name, arch, pkg string, useSignedDB bool, gnupgDir *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RepoRemove", name, arch, pkg, useSignedDB, gnupgDir)
	ret0, _ := ret[0].(error)
	return ret0
}

// RepoRemove indicates an expected call of RepoRemove.
func (mr *MockStoreMockRecorder) RepoRemove(name, arch, pkg, useSignedDB, gnupgDir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RepoRemove", reflect.TypeOf((*MockStore)(nil).RepoRemove), name, arch, pkg, useSignedDB, gnupgDir)
}

// StoreFile mocks base method.
func (m *MockStore) StoreFile(arg0, arch string, file stream.SeekFile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreFile", arg0, arch, file)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreFile indicates an expected call of StoreFile.
func (mr *MockStoreMockRecorder) StoreFile(arg0, arch, file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreFile", reflect.TypeOf((*MockStore)(nil).StoreFile), arg0, arch, file)
}

// StoreFileWithSignedURL mocks base method.
func (m *MockStore) StoreFileWithSignedURL(arg0, arch, name string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreFileWithSignedURL", arg0, arch, name)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StoreFileWithSignedURL indicates an expected call of StoreFileWithSignedURL.
func (mr *MockStoreMockRecorder) StoreFileWithSignedURL(arg0, arch, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreFileWithSignedURL", reflect.TypeOf((*MockStore)(nil).StoreFileWithSignedURL), arg0, arch, name)
}

// MockNameStore is a mock of NameStore interface.
type MockNameStore struct {
	ctrl     *gomock.Controller
	recorder *MockNameStoreMockRecorder
	isgomock struct{}
}

// MockNameStoreMockRecorder is the mock recorder for MockNameStore.
type MockNameStoreMockRecorder struct {
	mock *MockNameStore
}

// NewMockNameStore creates a new mock instance.
func NewMockNameStore(ctrl *gomock.Controller) *MockNameStore {
	mock := &MockNameStore{ctrl: ctrl}
	mock.recorder = &MockNameStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNameStore) EXPECT() *MockNameStoreMockRecorder {
	return m.recorder
}

// DeletePackageFileEntry mocks base method.
func (m *MockNameStore) DeletePackageFileEntry(packageName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePackageFileEntry", packageName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePackageFileEntry indicates an expected call of DeletePackageFileEntry.
func (mr *MockNameStoreMockRecorder) DeletePackageFileEntry(packageName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePackageFileEntry", reflect.TypeOf((*MockNameStore)(nil).DeletePackageFileEntry), packageName)
}

// PackageFile mocks base method.
func (m *MockNameStore) PackageFile(name string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PackageFile", name)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PackageFile indicates an expected call of PackageFile.
func (mr *MockNameStoreMockRecorder) PackageFile(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PackageFile", reflect.TypeOf((*MockNameStore)(nil).PackageFile), name)
}

// StorePackageFile mocks base method.
func (m *MockNameStore) StorePackageFile(packageName, filePath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StorePackageFile", packageName, filePath)
	ret0, _ := ret[0].(error)
	return ret0
}

// StorePackageFile indicates an expected call of StorePackageFile.
func (mr *MockNameStoreMockRecorder) StorePackageFile(packageName, filePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StorePackageFile", reflect.TypeOf((*MockNameStore)(nil).StorePackageFile), packageName, filePath)
}

// MockBinaryRepository is a mock of BinaryRepository interface.
type MockBinaryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBinaryRepositoryMockRecorder
	isgomock struct{}
}

// MockBinaryRepositoryMockRecorder is the mock recorder for MockBinaryRepository.
type MockBinaryRepositoryMockRecorder struct {
	mock *MockBinaryRepository
}

// NewMockBinaryRepository creates a new mock instance.
func NewMockBinaryRepository(ctrl *gomock.Controller) *MockBinaryRepository {
	mock := &MockBinaryRepository{ctrl: ctrl}
	mock.recorder = &MockBinaryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBinaryRepository) EXPECT() *MockBinaryRepositoryMockRecorder {
	return m.recorder
}

// Arches mocks base method.
func (m *MockBinaryRepository) Arches(arg0 string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Arches", arg0)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Arches indicates an expected call of Arches.
func (mr *MockBinaryRepositoryMockRecorder) Arches(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Arches", reflect.TypeOf((*MockBinaryRepository)(nil).Arches), arg0)
}

// DeleteFile mocks base method.
func (m *MockBinaryRepository) DeleteFile(arg0, arch, file string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFile", arg0, arch, file)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFile indicates an expected call of DeleteFile.
func (mr *MockBinaryRepositoryMockRecorder) DeleteFile(arg0, arch, file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFile", reflect.TypeOf((*MockBinaryRepository)(nil).DeleteFile), arg0, arch, file)
}

// FetchDB mocks base method.
func (m *MockBinaryRepository) FetchDB(repoName, archName string) (stream.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchDB", repoName, archName)
	ret0, _ := ret[0].(stream.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchDB indicates an expected call of FetchDB.
func (mr *MockBinaryRepositoryMockRecorder) FetchDB(repoName, archName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchDB", reflect.TypeOf((*MockBinaryRepository)(nil).FetchDB), repoName, archName)
}

// FetchFile mocks base method.
func (m *MockBinaryRepository) FetchFile(arg0, arch, file string) (stream.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchFile", arg0, arch, file)
	ret0, _ := ret[0].(stream.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchFile indicates an expected call of FetchFile.
func (mr *MockBinaryRepositoryMockRecorder) FetchFile(arg0, arch, file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchFile", reflect.TypeOf((*MockBinaryRepository)(nil).FetchFile), arg0, arch, file)
}

// Files mocks base method.
func (m *MockBinaryRepository) Files(arg0, arch string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Files", arg0, arch)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Files indicates an expected call of Files.
func (mr *MockBinaryRepositoryMockRecorder) Files(arg0, arch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Files", reflect.TypeOf((*MockBinaryRepository)(nil).Files), arg0, arch)
}

// Init mocks base method.
func (m *MockBinaryRepository) Init(name string, useSignedDB bool, gnupgDir *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init", name, useSignedDB, gnupgDir)
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockBinaryRepositoryMockRecorder) Init(name, useSignedDB, gnupgDir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockBinaryRepository)(nil).Init), name, useSignedDB, gnupgDir)
}

// InitArch mocks base method.
func (m *MockBinaryRepository) InitArch(name, arch string, useSignedDB bool, gnupgDir *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitArch", name, arch, useSignedDB, gnupgDir)
	ret0, _ := ret[0].(error)
	return ret0
}

// InitArch indicates an expected call of InitArch.
func (mr *MockBinaryRepositoryMockRecorder) InitArch(name, arch, useSignedDB, gnupgDir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitArch", reflect.TypeOf((*MockBinaryRepository)(nil).InitArch), name, arch, useSignedDB, gnupgDir)
}

// PkgFiles mocks base method.
func (m *MockBinaryRepository) PkgFiles(repoName, archName, pkgName string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PkgFiles", repoName, archName, pkgName)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PkgFiles indicates an expected call of PkgFiles.
func (mr *MockBinaryRepositoryMockRecorder) PkgFiles(repoName, archName, pkgName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PkgFiles", reflect.TypeOf((*MockBinaryRepository)(nil).PkgFiles), repoName, archName, pkgName)
}

// PkgNames mocks base method.
func (m *MockBinaryRepository) PkgNames(repoName, archName string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PkgNames", repoName, archName)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PkgNames indicates an expected call of PkgNames.
func (mr *MockBinaryRepositoryMockRecorder) PkgNames(repoName, archName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PkgNames", reflect.TypeOf((*MockBinaryRepository)(nil).PkgNames), repoName, archName)
}

// RemoteRepo mocks base method.
func (m *MockBinaryRepository) RemoteRepo(name, arch string) (*repo.RemoteRepo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoteRepo", name, arch)
	ret0, _ := ret[0].(*repo.RemoteRepo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoteRepo indicates an expected call of RemoteRepo.
func (mr *MockBinaryRepositoryMockRecorder) RemoteRepo(name, arch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoteRepo", reflect.TypeOf((*MockBinaryRepository)(nil).RemoteRepo), name, arch)
}

// RepoAdd mocks base method.
func (m *MockBinaryRepository) RepoAdd(name, arch string, pkg, sig stream.SeekFile, useSignedDB bool, gnupgDir *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RepoAdd", name, arch, pkg, sig, useSignedDB, gnupgDir)
	ret0, _ := ret[0].(error)
	return ret0
}

// RepoAdd indicates an expected call of RepoAdd.
func (mr *MockBinaryRepositoryMockRecorder) RepoAdd(name, arch, pkg, sig, useSignedDB, gnupgDir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RepoAdd", reflect.TypeOf((*MockBinaryRepository)(nil).RepoAdd), name, arch, pkg, sig, useSignedDB, gnupgDir)
}

// RepoNames mocks base method.
func (m *MockBinaryRepository) RepoNames() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RepoNames")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RepoNames indicates an expected call of RepoNames.
func (mr *MockBinaryRepositoryMockRecorder) RepoNames() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RepoNames", reflect.TypeOf((*MockBinaryRepository)(nil).RepoNames))
}

// RepoRemove mocks base method.
func (m *MockBinaryRepository) RepoRemove(name, arch, pkg string, useSignedDB bool, gnupgDir *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RepoRemove", name, arch, pkg, useSignedDB, gnupgDir)
	ret0, _ := ret[0].(error)
	return ret0
}

// RepoRemove indicates an expected call of RepoRemove.
func (mr *MockBinaryRepositoryMockRecorder) RepoRemove(name, arch, pkg, useSignedDB, gnupgDir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RepoRemove", reflect.TypeOf((*MockBinaryRepository)(nil).RepoRemove), name, arch, pkg, useSignedDB, gnupgDir)
}

// StoreFile mocks base method.
func (m *MockBinaryRepository) StoreFile(arg0, arch string, file stream.SeekFile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreFile", arg0, arch, file)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreFile indicates an expected call of StoreFile.
func (mr *MockBinaryRepositoryMockRecorder) StoreFile(arg0, arch, file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreFile", reflect.TypeOf((*MockBinaryRepository)(nil).StoreFile), arg0, arch, file)
}

// StoreFileWithSignedURL mocks base method.
func (m *MockBinaryRepository) StoreFileWithSignedURL(arg0, arch, name string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreFileWithSignedURL", arg0, arch, name)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StoreFileWithSignedURL indicates an expected call of StoreFileWithSignedURL.
func (mr *MockBinaryRepositoryMockRecorder) StoreFileWithSignedURL(arg0, arch, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreFileWithSignedURL", reflect.TypeOf((*MockBinaryRepository)(nil).StoreFileWithSignedURL), arg0, arch, name)
}

// VerifyPkgRepo mocks base method.
func (m *MockBinaryRepository) VerifyPkgRepo(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyPkgRepo", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyPkgRepo indicates an expected call of VerifyPkgRepo.
func (mr *MockBinaryRepositoryMockRecorder) VerifyPkgRepo(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyPkgRepo", reflect.TypeOf((*MockBinaryRepository)(nil).VerifyPkgRepo), name)
}
