// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=../test/mocks/repository.go -package=mocks -aux_files=github.com/Hayao0819/Kamisato/ayato/repository/blob=blob/blob.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	repository "github.com/Hayao0819/Kamisato/ayato/repository"
	blob "github.com/Hayao0819/Kamisato/ayato/repository/blob"
	stream "github.com/Hayao0819/Kamisato/ayato/stream"
	repo "github.com/Hayao0819/Kamisato/pkg/pacman/repo"
	gomock "go.uber.org/mock/gomock"
)

// MockBinaryRepository is a mock of BinaryRepository interface.
type MockBinaryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBinaryRepositoryMockRecorder
	isgomock struct{}
}

// MockBinaryRepositoryMockRecorder is the mock recorder for MockBinaryRepository.
type MockBinaryRepositoryMockRecorder struct {
	mock *MockBinaryRepository
}

// NewMockBinaryRepository creates a new mock instance.
func NewMockBinaryRepository(ctrl *gomock.Controller) *MockBinaryRepository {
	mock := &MockBinaryRepository{ctrl: ctrl}
	mock.recorder = &MockBinaryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBinaryRepository) EXPECT() *MockBinaryRepositoryMockRecorder {
	return m.recorder
}

// ApplyUpstreamSnapshot mocks base method.
func (m *MockBinaryRepository) ApplyUpstreamSnapshot(name, arch string, dbGz, filesGz []byte, etag, lastModified string, useSignedDB bool) (repo.DBDiff, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyUpstreamSnapshot", name, arch, dbGz, filesGz, etag, lastModified, useSignedDB)
	ret0, _ := ret[0].(repo.DBDiff)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApplyUpstreamSnapshot indicates an expected call of ApplyUpstreamSnapshot.
func (mr *MockBinaryRepositoryMockRecorder) ApplyUpstreamSnapshot(name, arch, dbGz, filesGz, etag, lastModified, useSignedDB any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyUpstreamSnapshot", reflect.TypeOf((*MockBinaryRepository)(nil).ApplyUpstreamSnapshot), name, arch, dbGz, filesGz, etag, lastModified, useSignedDB)
}

// Arches mocks base method.
func (m *MockBinaryRepository) Arches(arg0 string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Arches", arg0)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Arches indicates an expected call of Arches.
func (mr *MockBinaryRepositoryMockRecorder) Arches(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Arches", reflect.TypeOf((*MockBinaryRepository)(nil).Arches), arg0)
}

// BackfillSignatures mocks base method.
func (m *MockBinaryRepository) BackfillSignatures(name, arch string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BackfillSignatures", name, arch)
	ret0, _ := ret[0].(error)
	return ret0
}

// BackfillSignatures indicates an expected call of BackfillSignatures.
func (mr *MockBinaryRepositoryMockRecorder) BackfillSignatures(name, arch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BackfillSignatures", reflect.TypeOf((*MockBinaryRepository)(nil).BackfillSignatures), name, arch)
}

// DeleteFile mocks base method.
func (m *MockBinaryRepository) DeleteFile(arg0, arch, file string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFile", arg0, arch, file)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFile indicates an expected call of DeleteFile.
func (mr *MockBinaryRepositoryMockRecorder) DeleteFile(arg0, arch, file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFile", reflect.TypeOf((*MockBinaryRepository)(nil).DeleteFile), arg0, arch, file)
}

// DeleteOrphanIfUnchanged mocks base method.
func (m *MockBinaryRepository) DeleteOrphanIfUnchanged(name, arch string, expected blob.FileInfo, cutoff time.Time) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOrphanIfUnchanged", name, arch, expected, cutoff)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteOrphanIfUnchanged indicates an expected call of DeleteOrphanIfUnchanged.
func (mr *MockBinaryRepositoryMockRecorder) DeleteOrphanIfUnchanged(name, arch, expected, cutoff any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrphanIfUnchanged", reflect.TypeOf((*MockBinaryRepository)(nil).DeleteOrphanIfUnchanged), name, arch, expected, cutoff)
}

// FetchDB mocks base method.
func (m *MockBinaryRepository) FetchDB(repoName, archName string) (stream.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchDB", repoName, archName)
	ret0, _ := ret[0].(stream.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchDB indicates an expected call of FetchDB.
func (mr *MockBinaryRepositoryMockRecorder) FetchDB(repoName, archName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchDB", reflect.TypeOf((*MockBinaryRepository)(nil).FetchDB), repoName, archName)
}

// FetchFile mocks base method.
func (m *MockBinaryRepository) FetchFile(arg0, arch, file string) (stream.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchFile", arg0, arch, file)
	ret0, _ := ret[0].(stream.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchFile indicates an expected call of FetchFile.
func (mr *MockBinaryRepositoryMockRecorder) FetchFile(arg0, arch, file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchFile", reflect.TypeOf((*MockBinaryRepository)(nil).FetchFile), arg0, arch, file)
}

// FetchFileWithETag mocks base method.
func (m *MockBinaryRepository) FetchFileWithETag(arg0, arch, file string) (stream.File, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchFileWithETag", arg0, arch, file)
	ret0, _ := ret[0].(stream.File)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FetchFileWithETag indicates an expected call of FetchFileWithETag.
func (mr *MockBinaryRepositoryMockRecorder) FetchFileWithETag(arg0, arch, file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchFileWithETag", reflect.TypeOf((*MockBinaryRepository)(nil).FetchFileWithETag), arg0, arch, file)
}

// FetchFileWithMeta mocks base method.
func (m *MockBinaryRepository) FetchFileWithMeta(arg0, arch, file string) (stream.File, blob.FileMeta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchFileWithMeta", arg0, arch, file)
	ret0, _ := ret[0].(stream.File)
	ret1, _ := ret[1].(blob.FileMeta)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FetchFileWithMeta indicates an expected call of FetchFileWithMeta.
func (mr *MockBinaryRepositoryMockRecorder) FetchFileWithMeta(arg0, arch, file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchFileWithMeta", reflect.TypeOf((*MockBinaryRepository)(nil).FetchFileWithMeta), arg0, arch, file)
}

// Files mocks base method.
func (m *MockBinaryRepository) Files(arg0, arch string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Files", arg0, arch)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Files indicates an expected call of Files.
func (mr *MockBinaryRepositoryMockRecorder) Files(arg0, arch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Files", reflect.TypeOf((*MockBinaryRepository)(nil).Files), arg0, arch)
}

// FilesWithMeta mocks base method.
func (m *MockBinaryRepository) FilesWithMeta(arg0, arch string) ([]blob.FileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilesWithMeta", arg0, arch)
	ret0, _ := ret[0].([]blob.FileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilesWithMeta indicates an expected call of FilesWithMeta.
func (mr *MockBinaryRepositoryMockRecorder) FilesWithMeta(arg0, arch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilesWithMeta", reflect.TypeOf((*MockBinaryRepository)(nil).FilesWithMeta), arg0, arch)
}

// InitArch mocks base method.
func (m *MockBinaryRepository) InitArch(name, arch string, useSignedDB bool, gnupgDir *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitArch", name, arch, useSignedDB, gnupgDir)
	ret0, _ := ret[0].(error)
	return ret0
}

// InitArch indicates an expected call of InitArch.
func (mr *MockBinaryRepositoryMockRecorder) InitArch(name, arch, useSignedDB, gnupgDir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitArch", reflect.TypeOf((*MockBinaryRepository)(nil).InitArch), name, arch, useSignedDB, gnupgDir)
}

// PkgFiles mocks base method.
func (m *MockBinaryRepository) PkgFiles(repoName, archName, pkgName string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PkgFiles", repoName, archName, pkgName)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PkgFiles indicates an expected call of PkgFiles.
func (mr *MockBinaryRepositoryMockRecorder) PkgFiles(repoName, archName, pkgName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PkgFiles", reflect.TypeOf((*MockBinaryRepository)(nil).PkgFiles), repoName, archName, pkgName)
}

// PkgNames mocks base method.
func (m *MockBinaryRepository) PkgNames(repoName, archName string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PkgNames", repoName, archName)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PkgNames indicates an expected call of PkgNames.
func (mr *MockBinaryRepositoryMockRecorder) PkgNames(repoName, archName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PkgNames", reflect.TypeOf((*MockBinaryRepository)(nil).PkgNames), repoName, archName)
}

// RebuildMerged mocks base method.
func (m *MockBinaryRepository) RebuildMerged(name, arch string, useSignedDB bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RebuildMerged", name, arch, useSignedDB)
	ret0, _ := ret[0].(error)
	return ret0
}

// RebuildMerged indicates an expected call of RebuildMerged.
func (mr *MockBinaryRepositoryMockRecorder) RebuildMerged(name, arch, useSignedDB any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RebuildMerged", reflect.TypeOf((*MockBinaryRepository)(nil).RebuildMerged), name, arch, useSignedDB)
}

// ReconcileDB mocks base method.
func (m *MockBinaryRepository) ReconcileDB(name, arch string, useSignedDB bool, gnupgDir *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReconcileDB", name, arch, useSignedDB, gnupgDir)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReconcileDB indicates an expected call of ReconcileDB.
func (mr *MockBinaryRepositoryMockRecorder) ReconcileDB(name, arch, useSignedDB, gnupgDir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReconcileDB", reflect.TypeOf((*MockBinaryRepository)(nil).ReconcileDB), name, arch, useSignedDB, gnupgDir)
}

// RemoteRepo mocks base method.
func (m *MockBinaryRepository) RemoteRepo(name, arch string) (*repo.RemoteRepo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoteRepo", name, arch)
	ret0, _ := ret[0].(*repo.RemoteRepo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoteRepo indicates an expected call of RemoteRepo.
func (mr *MockBinaryRepositoryMockRecorder) RemoteRepo(name, arch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoteRepo", reflect.TypeOf((*MockBinaryRepository)(nil).RemoteRepo), name, arch)
}

// RepoAdd mocks base method.
func (m *MockBinaryRepository) RepoAdd(name, arch string, pkg, sig stream.SeekFile, useSignedDB bool, gnupgDir *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RepoAdd", name, arch, pkg, sig, useSignedDB, gnupgDir)
	ret0, _ := ret[0].(error)
	return ret0
}

// RepoAdd indicates an expected call of RepoAdd.
func (mr *MockBinaryRepositoryMockRecorder) RepoAdd(name, arch, pkg, sig, useSignedDB, gnupgDir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RepoAdd", reflect.TypeOf((*MockBinaryRepository)(nil).RepoAdd), name, arch, pkg, sig, useSignedDB, gnupgDir)
}

// RepoAddBatch mocks base method.
func (m *MockBinaryRepository) RepoAddBatch(name, arch string, items []repository.RepoAddItem, useSignedDB bool, gnupgDir *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RepoAddBatch", name, arch, items, useSignedDB, gnupgDir)
	ret0, _ := ret[0].(error)
	return ret0
}

// RepoAddBatch indicates an expected call of RepoAddBatch.
func (mr *MockBinaryRepositoryMockRecorder) RepoAddBatch(name, arch, items, useSignedDB, gnupgDir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RepoAddBatch", reflect.TypeOf((*MockBinaryRepository)(nil).RepoAddBatch), name, arch, items, useSignedDB, gnupgDir)
}

// RepoNames mocks base method.
func (m *MockBinaryRepository) RepoNames() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RepoNames")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RepoNames indicates an expected call of RepoNames.
func (mr *MockBinaryRepositoryMockRecorder) RepoNames() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RepoNames", reflect.TypeOf((*MockBinaryRepository)(nil).RepoNames))
}

// RepoRemove mocks base method.
func (m *MockBinaryRepository) RepoRemove(name, arch, pkg string, useSignedDB bool, gnupgDir *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RepoRemove", name, arch, pkg, useSignedDB, gnupgDir)
	ret0, _ := ret[0].(error)
	return ret0
}

// RepoRemove indicates an expected call of RepoRemove.
func (mr *MockBinaryRepositoryMockRecorder) RepoRemove(name, arch, pkg, useSignedDB, gnupgDir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RepoRemove", reflect.TypeOf((*MockBinaryRepository)(nil).RepoRemove), name, arch, pkg, useSignedDB, gnupgDir)
}

// RepoRemoveIfMatch mocks base method.
func (m *MockBinaryRepository) RepoRemoveIfMatch(name, arch, pkg, expectedVersion, expectedFile string, useSignedDB bool, gnupgDir *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RepoRemoveIfMatch", name, arch, pkg, expectedVersion, expectedFile, useSignedDB, gnupgDir)
	ret0, _ := ret[0].(error)
	return ret0
}

// RepoRemoveIfMatch indicates an expected call of RepoRemoveIfMatch.
func (mr *MockBinaryRepositoryMockRecorder) RepoRemoveIfMatch(name, arch, pkg, expectedVersion, expectedFile, useSignedDB, gnupgDir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RepoRemoveIfMatch", reflect.TypeOf((*MockBinaryRepository)(nil).RepoRemoveIfMatch), name, arch, pkg, expectedVersion, expectedFile, useSignedDB, gnupgDir)
}

// StoreFile mocks base method.
func (m *MockBinaryRepository) StoreFile(arg0, arch string, file stream.SeekFile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreFile", arg0, arch, file)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreFile indicates an expected call of StoreFile.
func (mr *MockBinaryRepositoryMockRecorder) StoreFile(arg0, arch, file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreFile", reflect.TypeOf((*MockBinaryRepository)(nil).StoreFile), arg0, arch, file)
}

// StoreFileIfMatch mocks base method.
func (m *MockBinaryRepository) StoreFileIfMatch(arg0, arch string, file stream.SeekFile, etag string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreFileIfMatch", arg0, arch, file, etag)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreFileIfMatch indicates an expected call of StoreFileIfMatch.
func (mr *MockBinaryRepositoryMockRecorder) StoreFileIfMatch(arg0, arch, file, etag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreFileIfMatch", reflect.TypeOf((*MockBinaryRepository)(nil).StoreFileIfMatch), arg0, arch, file, etag)
}

// StoreFileImmutable mocks base method.
func (m *MockBinaryRepository) StoreFileImmutable(name, arch string, file stream.SeekFile) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreFileImmutable", name, arch, file)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StoreFileImmutable indicates an expected call of StoreFileImmutable.
func (mr *MockBinaryRepositoryMockRecorder) StoreFileImmutable(name, arch, file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreFileImmutable", reflect.TypeOf((*MockBinaryRepository)(nil).StoreFileImmutable), name, arch, file)
}

// StoreFileWithSignedURL mocks base method.
func (m *MockBinaryRepository) StoreFileWithSignedURL(arg0, arch, name string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreFileWithSignedURL", arg0, arch, name)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StoreFileWithSignedURL indicates an expected call of StoreFileWithSignedURL.
func (mr *MockBinaryRepositoryMockRecorder) StoreFileWithSignedURL(arg0, arch, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreFileWithSignedURL", reflect.TypeOf((*MockBinaryRepository)(nil).StoreFileWithSignedURL), arg0, arch, name)
}

// UpstreamValidators mocks base method.
func (m *MockBinaryRepository) UpstreamValidators(name, arch string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpstreamValidators", name, arch)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UpstreamValidators indicates an expected call of UpstreamValidators.
func (mr *MockBinaryRepositoryMockRecorder) UpstreamValidators(name, arch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpstreamValidators", reflect.TypeOf((*MockBinaryRepository)(nil).UpstreamValidators), name, arch)
}

// VerifyPkgRepo mocks base method.
func (m *MockBinaryRepository) VerifyPkgRepo(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyPkgRepo", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyPkgRepo indicates an expected call of VerifyPkgRepo.
func (mr *MockBinaryRepositoryMockRecorder) VerifyPkgRepo(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyPkgRepo", reflect.TypeOf((*MockBinaryRepository)(nil).VerifyPkgRepo), name)
}
