// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=../test/mocks/service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	domain "github.com/Hayao0819/Kamisato/ayato/domain"
	repository "github.com/Hayao0819/Kamisato/ayato/repository"
	stream "github.com/Hayao0819/Kamisato/ayato/stream"
	raiou "github.com/Hayao0819/Kamisato/pkg/raiou"
	gomock "go.uber.org/mock/gomock"
)

// MockServicer is a mock of Servicer interface.
type MockServicer struct {
	ctrl     *gomock.Controller
	recorder *MockServicerMockRecorder
	isgomock struct{}
}

// MockServicerMockRecorder is the mock recorder for MockServicer.
type MockServicerMockRecorder struct {
	mock *MockServicer
}

// NewMockServicer creates a new mock instance.
func NewMockServicer(ctrl *gomock.Controller) *MockServicer {
	mock := &MockServicer{ctrl: ctrl}
	mock.recorder = &MockServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServicer) EXPECT() *MockServicerMockRecorder {
	return m.recorder
}

// AddAdmin mocks base method.
func (m *MockServicer) AddAdmin(id int64, login string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAdmin", id, login)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddAdmin indicates an expected call of AddAdmin.
func (mr *MockServicerMockRecorder) AddAdmin(id, login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAdmin", reflect.TypeOf((*MockServicer)(nil).AddAdmin), id, login)
}

// Arches mocks base method.
func (m *MockServicer) Arches(repo string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Arches", repo)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Arches indicates an expected call of Arches.
func (mr *MockServicerMockRecorder) Arches(repo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Arches", reflect.TypeOf((*MockServicer)(nil).Arches), repo)
}

// GetFile mocks base method.
func (m *MockServicer) GetFile(repoName, archName, name string) (stream.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFile", repoName, archName, name)
	ret0, _ := ret[0].(stream.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFile indicates an expected call of GetFile.
func (mr *MockServicerMockRecorder) GetFile(repoName, archName, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFile", reflect.TypeOf((*MockServicer)(nil).GetFile), repoName, archName, name)
}

// InitAll mocks base method.
func (m *MockServicer) InitAll() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitAll")
	ret0, _ := ret[0].(error)
	return ret0
}

// InitAll indicates an expected call of InitAll.
func (mr *MockServicerMockRecorder) InitAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitAll", reflect.TypeOf((*MockServicer)(nil).InitAll))
}

// IsAdmin mocks base method.
func (m *MockServicer) IsAdmin(id int64) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAdmin", id)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsAdmin indicates an expected call of IsAdmin.
func (mr *MockServicerMockRecorder) IsAdmin(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAdmin", reflect.TypeOf((*MockServicer)(nil).IsAdmin), id)
}

// ListAdmins mocks base method.
func (m *MockServicer) ListAdmins() ([]repository.AllowedAdmin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAdmins")
	ret0, _ := ret[0].([]repository.AllowedAdmin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAdmins indicates an expected call of ListAdmins.
func (mr *MockServicerMockRecorder) ListAdmins() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAdmins", reflect.TypeOf((*MockServicer)(nil).ListAdmins))
}

// PkgDetail mocks base method.
func (m *MockServicer) PkgDetail(repo, arch, pkg string) (*raiou.PKGINFO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PkgDetail", repo, arch, pkg)
	ret0, _ := ret[0].(*raiou.PKGINFO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PkgDetail indicates an expected call of PkgDetail.
func (mr *MockServicerMockRecorder) PkgDetail(repo, arch, pkg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PkgDetail", reflect.TypeOf((*MockServicer)(nil).PkgDetail), repo, arch, pkg)
}

// PkgFiles mocks base method.
func (m *MockServicer) PkgFiles(repo, arch, pkg string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PkgFiles", repo, arch, pkg)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PkgFiles indicates an expected call of PkgFiles.
func (mr *MockServicerMockRecorder) PkgFiles(repo, arch, pkg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PkgFiles", reflect.TypeOf((*MockServicer)(nil).PkgFiles), repo, arch, pkg)
}

// Pkgs mocks base method.
func (m *MockServicer) Pkgs(repo, arch string) (*domain.PacmanPkgs, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pkgs", repo, arch)
	ret0, _ := ret[0].(*domain.PacmanPkgs)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Pkgs indicates an expected call of Pkgs.
func (mr *MockServicerMockRecorder) Pkgs(repo, arch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pkgs", reflect.TypeOf((*MockServicer)(nil).Pkgs), repo, arch)
}

// RemoveAdmin mocks base method.
func (m *MockServicer) RemoveAdmin(id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveAdmin", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveAdmin indicates an expected call of RemoveAdmin.
func (mr *MockServicerMockRecorder) RemoveAdmin(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAdmin", reflect.TypeOf((*MockServicer)(nil).RemoveAdmin), id)
}

// RemovePkg mocks base method.
func (m *MockServicer) RemovePkg(rname, arch, pkgname string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemovePkg", rname, arch, pkgname)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemovePkg indicates an expected call of RemovePkg.
func (mr *MockServicerMockRecorder) RemovePkg(rname, arch, pkgname any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemovePkg", reflect.TypeOf((*MockServicer)(nil).RemovePkg), rname, arch, pkgname)
}

// Repo mocks base method.
func (m *MockServicer) Repo(repo string) (*domain.PacmanRepo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Repo", repo)
	ret0, _ := ret[0].(*domain.PacmanRepo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Repo indicates an expected call of Repo.
func (mr *MockServicerMockRecorder) Repo(repo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Repo", reflect.TypeOf((*MockServicer)(nil).Repo), repo)
}

// RepoFileList mocks base method.
func (m *MockServicer) RepoFileList(repo, arch string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RepoFileList", repo, arch)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RepoFileList indicates an expected call of RepoFileList.
func (mr *MockServicerMockRecorder) RepoFileList(repo, arch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RepoFileList", reflect.TypeOf((*MockServicer)(nil).RepoFileList), repo, arch)
}

// RepoNames mocks base method.
func (m *MockServicer) RepoNames() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RepoNames")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RepoNames indicates an expected call of RepoNames.
func (mr *MockServicerMockRecorder) RepoNames() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RepoNames", reflect.TypeOf((*MockServicer)(nil).RepoNames))
}

// SeedBootstrapAdmin mocks base method.
func (m *MockServicer) SeedBootstrapAdmin(id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SeedBootstrapAdmin", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SeedBootstrapAdmin indicates an expected call of SeedBootstrapAdmin.
func (mr *MockServicerMockRecorder) SeedBootstrapAdmin(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SeedBootstrapAdmin", reflect.TypeOf((*MockServicer)(nil).SeedBootstrapAdmin), id)
}

// SignedURL mocks base method.
func (m *MockServicer) SignedURL(repo, arch, name string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignedURL", repo, arch, name)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignedURL indicates an expected call of SignedURL.
func (mr *MockServicerMockRecorder) SignedURL(repo, arch, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignedURL", reflect.TypeOf((*MockServicer)(nil).SignedURL), repo, arch, name)
}

// UploadFile mocks base method.
func (m *MockServicer) UploadFile(repo string, files *domain.UploadFiles) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadFile", repo, files)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadFile indicates an expected call of UploadFile.
func (mr *MockServicerMockRecorder) UploadFile(repo, files any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadFile", reflect.TypeOf((*MockServicer)(nil).UploadFile), repo, files)
}
