// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=../test/mocks/service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Hayao0819/Kamisato/miko/domain"
	joblog "github.com/Hayao0819/Kamisato/miko/joblog"
	gomock "go.uber.org/mock/gomock"
)

// MockServicer is a mock of Servicer interface.
type MockServicer struct {
	ctrl     *gomock.Controller
	recorder *MockServicerMockRecorder
	isgomock struct{}
}

// MockServicerMockRecorder is the mock recorder for MockServicer.
type MockServicerMockRecorder struct {
	mock *MockServicer
}

// NewMockServicer creates a new mock instance.
func NewMockServicer(ctrl *gomock.Controller) *MockServicer {
	mock := &MockServicer{ctrl: ctrl}
	mock.recorder = &MockServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServicer) EXPECT() *MockServicerMockRecorder {
	return m.recorder
}

// ArtifactDir mocks base method.
func (m *MockServicer) ArtifactDir(id string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ArtifactDir", id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ArtifactDir indicates an expected call of ArtifactDir.
func (mr *MockServicerMockRecorder) ArtifactDir(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ArtifactDir", reflect.TypeOf((*MockServicer)(nil).ArtifactDir), id)
}

// Cancel mocks base method.
func (m *MockServicer) Cancel(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cancel", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Cancel indicates an expected call of Cancel.
func (mr *MockServicerMockRecorder) Cancel(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockServicer)(nil).Cancel), id)
}

// List mocks base method.
func (m *MockServicer) List() []*domain.BuildJob {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]*domain.BuildJob)
	return ret0
}

// List indicates an expected call of List.
func (mr *MockServicerMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockServicer)(nil).List))
}

// LogBuffer mocks base method.
func (m *MockServicer) LogBuffer(id string) *joblog.Buffer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogBuffer", id)
	ret0, _ := ret[0].(*joblog.Buffer)
	return ret0
}

// LogBuffer indicates an expected call of LogBuffer.
func (mr *MockServicerMockRecorder) LogBuffer(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogBuffer", reflect.TypeOf((*MockServicer)(nil).LogBuffer), id)
}

// Run mocks base method.
func (m *MockServicer) Run(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Run", ctx)
}

// Run indicates an expected call of Run.
func (mr *MockServicerMockRecorder) Run(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockServicer)(nil).Run), ctx)
}

// Stats mocks base method.
func (m *MockServicer) Stats() domain.BuildStats {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stats")
	ret0, _ := ret[0].(domain.BuildStats)
	return ret0
}

// Stats indicates an expected call of Stats.
func (mr *MockServicerMockRecorder) Stats() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stats", reflect.TypeOf((*MockServicer)(nil).Stats))
}

// Status mocks base method.
func (m *MockServicer) Status(id string) (*domain.BuildJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status", id)
	ret0, _ := ret[0].(*domain.BuildJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Status indicates an expected call of Status.
func (mr *MockServicerMockRecorder) Status(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockServicer)(nil).Status), id)
}

// Submit mocks base method.
func (m *MockServicer) Submit(req *domain.BuildRequest) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Submit", req)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Submit indicates an expected call of Submit.
func (mr *MockServicerMockRecorder) Submit(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Submit", reflect.TypeOf((*MockServicer)(nil).Submit), req)
}
