package handler

import (
	"fmt"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/Hayao0819/Kamisato/ayato/httpapi"
	"github.com/gin-gonic/gin"
)

// mirrorEntry is one Server line plus the comments rendered above it.
type mirrorEntry struct {
	section string // ## section header grouping consecutive entries
	name    string // optional ## per-entry annotation above the Server line
	note    string // optional trailing annotation (appended after " — ")
	url     string // the Server = value (may contain $arch / $repo)
	active  bool   // false renders the line commented out (#Server = ...)
}

// MirrorlistHandler serves a pacman mirrorlist for a repo, advertising only this
// instance in the mainstream comment-rich style so a client can Include it
// verbatim.
func (h *RepositoryHandler) MirrorlistHandler(c *gin.Context) {
	repoName := c.Param("repo")
	// Validate against the servable repo set (tiers included) so the path we echo
	// into Server lines is one ayato actually serves, never an arbitrary string.
	if _, ok := h.catalog.Resolve(repoName); !ok {
		respondError(c, http.StatusNotFound, fmt.Sprintf("unknown repository %q", repoName))
		return
	}

	base, configured := h.mirrorBase(c)
	if !configured {
		// base came from the (spoofable) request Host; forbid shared caching so a
		// proxy cannot serve one client's Host-derived list to another.
		c.Header("Cache-Control", "no-store")
	}

	entries := []mirrorEntry{h.selfMirror(base, repoName)}
	c.String(http.StatusOK, renderMirrorlist(repoName, entries))
}

func (h *RepositoryHandler) selfMirror(base, repoName string) mirrorEntry {
	seg := repoName
	if h.settings.Mirror.UseRepoVar {
		seg = "$repo"
	}
	return mirrorEntry{
		section: mirrorHost(base) + " (this instance)",
		url:     base + h.settings.Mirror.ServerPath + "/" + seg + "/$arch",
		active:  !h.settings.Mirror.AllCommented,
	}
}

// mirrorBase resolves this instance's public base URL and whether it came from a
// configured origin (mirror.self_url, then auth self/public origin) rather than
// the spoofable request Host. X-Forwarded-* is not trusted (see externalBase).
func (h *RepositoryHandler) mirrorBase(c *gin.Context) (base string, configured bool) {
	if _, b, ok := httpapi.ParseOrigin(h.settings.Mirror.SelfURL); ok {
		return b, true
	}
	_, b := externalBase(h.settings.Auth, c)
	return strings.TrimRight(b, "/"), h.hasConfiguredOrigin()
}

// hasConfiguredOrigin reports whether an auth self/public origin is set, so a base
// derived via externalBase is stable rather than request-Host-derived.
func (h *RepositoryHandler) hasConfiguredOrigin() bool {
	if _, _, ok := httpapi.ParseOrigin(h.settings.Auth.SelfOrigin); ok {
		return true
	}
	_, _, ok := httpapi.ParseOrigin(h.settings.Auth.PublicOrigin)
	return ok
}

func mirrorHost(base string) string {
	if u, err := url.Parse(base); err == nil && u.Host != "" {
		return u.Host
	}
	return base
}

// renderMirrorlist formats entries in the mainstream mirrorlist style; output is
// LF-only.
func renderMirrorlist(repoName string, entries []mirrorEntry) string {
	var b strings.Builder
	fmt.Fprintf(&b, "##\n## %s repository mirrorlist\n## Generated by ayato on %s\n##\n",
		repoName, time.Now().UTC().Format("2006-01-02"))
	fmt.Fprintf(&b, "\n## Reference this file from /etc/pacman.conf:\n##   [%s]\n##   Include = /etc/pacman.d/%s-mirrorlist\n",
		repoName, repoName)
	b.WriteString("## Uncomment a Server line (remove the leading '#') to activate that mirror.\n")
	b.WriteString("## Servers are tried top-to-bottom; the first reachable one wins.\n")

	section := ""
	for _, e := range entries {
		if e.section != section {
			section = e.section
			fmt.Fprintf(&b, "\n## %s\n", section)
		}
		if e.name != "" {
			line := "## " + e.name
			if e.note != "" {
				line += " — " + e.note
			}
			b.WriteString(line + "\n")
		}
		if e.active {
			fmt.Fprintf(&b, "Server = %s\n", e.url)
		} else {
			fmt.Fprintf(&b, "#Server = %s\n", e.url)
		}
	}
	return b.String()
}
