package handler

import (
	"fmt"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/Hayao0819/Kamisato/ayato/domain"
	"github.com/gin-gonic/gin"
)

// mirrorEntry is one Server line plus the comments rendered above it.
type mirrorEntry struct {
	section string // ## section header grouping consecutive entries
	name    string // optional ## per-entry annotation above the Server line
	note    string // optional trailing annotation (appended after " — ")
	url     string // the Server = value (may contain $arch / $repo)
	active  bool   // false renders the line commented out (#Server = ...)
}

// MirrorlistHandler serves a pacman mirrorlist for a repo. Phase 1 advertises only
// this instance, formatted in the comment-rich style of the mainstream Arch
// mirrorlists (a four-line ## header block, a usage stanza, section headers) so a
// client can Include it verbatim. Peers and health filtering are future work.
func (h *Handler) MirrorlistHandler(c *gin.Context) {
	repoName := c.Param("repo")
	// Validate against the servable repo set (tiers included) so the path we echo
	// into Server lines is one ayato actually serves, never an arbitrary string.
	if h.cfg == nil || h.cfg.ResolveRepo(repoName) == nil {
		c.JSON(http.StatusNotFound, domain.APIError{Message: fmt.Sprintf("unknown repository %q", repoName)})
		return
	}

	base, configured := h.mirrorBase(c)
	if !configured {
		// base came from the (spoofable) request Host; forbid shared caching so a
		// proxy cannot serve one client's Host-derived list to another. Set
		// mirror.self_url (or an auth origin) in production for a stable base.
		c.Header("Cache-Control", "no-store")
	}

	entries := []mirrorEntry{h.selfMirror(base, repoName)}
	c.String(http.StatusOK, renderMirrorlist(repoName, entries))
}

// selfMirror builds this instance's own Server entry. Precondition: h.cfg != nil
// (MirrorlistHandler gates it).
func (h *Handler) selfMirror(base, repoName string) mirrorEntry {
	seg := repoName
	if h.cfg.Mirror.UseRepoVar {
		seg = "$repo"
	}
	return mirrorEntry{
		section: mirrorHost(base) + " (this instance)",
		url:     base + h.cfg.Mirror.ServerPath() + "/" + seg + "/$arch",
		active:  !h.cfg.Mirror.AllCommented,
	}
}

// mirrorBase resolves this instance's public base URL and whether it came from a
// configured origin (mirror.self_url, then auth self/public origin) rather than
// the spoofable request Host. X-Forwarded-* is not trusted (see externalBase).
func (h *Handler) mirrorBase(c *gin.Context) (base string, configured bool) {
	if h.cfg != nil {
		if _, b, ok := originOf(h.cfg.Mirror.SelfURL); ok {
			return b, true
		}
	}
	_, b := h.externalBase(c)
	return strings.TrimRight(b, "/"), h.hasConfiguredOrigin()
}

// hasConfiguredOrigin reports whether an auth self/public origin is set, so a base
// derived via externalBase is stable rather than request-Host-derived.
func (h *Handler) hasConfiguredOrigin() bool {
	if h.cfg == nil {
		return false
	}
	if _, _, ok := originOf(h.cfg.Auth.SelfOrigin); ok {
		return true
	}
	_, _, ok := originOf(h.cfg.Auth.PublicOrigin)
	return ok
}

// mirrorHost returns a base URL's host for annotation, or the raw base if it does
// not parse.
func mirrorHost(base string) string {
	if u, err := url.Parse(base); err == nil && u.Host != "" {
		return u.Host
	}
	return base
}

// renderMirrorlist formats entries in the mainstream mirrorlist style: a four-line
// ## header block, a blank line, a usage stanza, then ## section headers above
// each Server line. Inactive entries render commented out. Output is LF-only.
func renderMirrorlist(repoName string, entries []mirrorEntry) string {
	var b strings.Builder
	fmt.Fprintf(&b, "##\n## %s repository mirrorlist\n## Generated by ayato on %s\n##\n",
		repoName, time.Now().UTC().Format("2006-01-02"))
	fmt.Fprintf(&b, "\n## Reference this file from /etc/pacman.conf:\n##   [%s]\n##   Include = /etc/pacman.d/%s-mirrorlist\n",
		repoName, repoName)
	b.WriteString("## Uncomment a Server line (remove the leading '#') to activate that mirror.\n")
	b.WriteString("## Servers are tried top-to-bottom; the first reachable one wins.\n")

	section := ""
	for _, e := range entries {
		if e.section != section {
			section = e.section
			fmt.Fprintf(&b, "\n## %s\n", section)
		}
		if e.name != "" {
			line := "## " + e.name
			if e.note != "" {
				line += " — " + e.note
			}
			b.WriteString(line + "\n")
		}
		if e.active {
			fmt.Fprintf(&b, "Server = %s\n", e.url)
		} else {
			fmt.Fprintf(&b, "#Server = %s\n", e.url)
		}
	}
	return b.String()
}
