package handler

import (
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
	"time"

	"github.com/gin-gonic/gin"

	"github.com/Hayao0819/Kamisato/internal/conf"
)

func mirrorlistHandler(cfg *conf.AyatoConfig) *gin.Engine {
	gin.SetMode(gin.TestMode)
	h := &Handler{cfg: cfg}
	r := gin.New()
	r.GET("/repo/:repo/mirrorlist", h.MirrorlistHandler)
	return r
}

func getMirrorlist(r *gin.Engine, repo string) *httptest.ResponseRecorder {
	w := httptest.NewRecorder()
	req := httptest.NewRequest(http.MethodGet, "/repo/"+repo+"/mirrorlist", nil)
	req.Host = "repo.example"
	r.ServeHTTP(w, req)
	return w
}

func TestMirrorlistHandler_SelfEntry(t *testing.T) {
	cfg := &conf.AyatoConfig{
		Repos:  []conf.BinRepoConfig{{Name: "myrepo"}},
		Mirror: conf.MirrorConfig{SelfURL: "https://repo.example"},
	}
	w := getMirrorlist(mirrorlistHandler(cfg), "myrepo")
	if w.Code != http.StatusOK {
		t.Fatalf("status = %d, want 200", w.Code)
	}
	if ct := w.Header().Get("Content-Type"); !strings.HasPrefix(ct, "text/plain") {
		t.Errorf("Content-Type = %q, want text/plain", ct)
	}
	body := w.Body.String()

	// Comment-rich header block and usage comments, like the mainstream lists.
	for _, want := range []string{
		"## myrepo repository mirrorlist",
		"## Generated by ayato on ",
		"Include = /etc/pacman.d/myrepo-mirrorlist",
		"## repo.example (this instance)", // host is the section header for the self entry
	} {
		if !strings.Contains(body, want) {
			t.Errorf("body missing %q\n---\n%s", want, body)
		}
	}
	// Date-only generation stamp (no clock), matching the mainstream mirrorlists.
	if strings.Contains(body, "Generated by ayato on "+time.Now().UTC().Format("2006-01-02")+"T") {
		t.Errorf("generation stamp should be date-only, got a datetime\n---\n%s", body)
	}
	// A configured self_url is a stable base: no anti-cache header needed.
	if cc := w.Header().Get("Cache-Control"); cc != "" {
		t.Errorf("Cache-Control = %q, want empty when self_url is set", cc)
	}
	// The self Server line: repo name baked in (default), $arch left literal.
	if want := "Server = https://repo.example/repo/myrepo/$arch"; !strings.Contains(body, want) {
		t.Errorf("body missing %q\n---\n%s", want, body)
	}
	// Active by default (not commented).
	if strings.Contains(body, "#Server = https://repo.example/repo/myrepo/$arch") {
		t.Errorf("self entry should be active, got commented\n---\n%s", body)
	}
}

func TestMirrorlistHandler_UnknownRepo(t *testing.T) {
	cfg := &conf.AyatoConfig{Repos: []conf.BinRepoConfig{{Name: "myrepo"}}}
	w := getMirrorlist(mirrorlistHandler(cfg), "nope")
	if w.Code != http.StatusNotFound {
		t.Fatalf("status = %d, want 404", w.Code)
	}
}

func TestMirrorlistHandler_HostFallback(t *testing.T) {
	// No self_url configured: base falls back to the request host.
	cfg := &conf.AyatoConfig{Repos: []conf.BinRepoConfig{{Name: "myrepo"}}}
	w := getMirrorlist(mirrorlistHandler(cfg), "myrepo")
	body := w.Body.String()
	if want := "Server = http://repo.example/repo/myrepo/$arch"; !strings.Contains(body, want) {
		t.Errorf("host fallback missing %q\n---\n%s", want, body)
	}
	// Host-derived base must not be shared-cached (poisoning guard).
	if cc := w.Header().Get("Cache-Control"); cc != "no-store" {
		t.Errorf("Cache-Control = %q, want no-store on host fallback", cc)
	}
}

func TestMirrorlistHandler_Options(t *testing.T) {
	cfg := &conf.AyatoConfig{
		Repos: []conf.BinRepoConfig{{Name: "myrepo"}},
		Mirror: conf.MirrorConfig{
			SelfURL:      "https://repo.example",
			RepoPath:     "/arch",
			UseRepoVar:   true,
			AllCommented: true,
		},
	}
	body := getMirrorlist(mirrorlistHandler(cfg), "myrepo").Body.String()
	// $repo variable, custom path prefix, and commented-out (opt-in) all apply.
	if want := "#Server = https://repo.example/arch/$repo/$arch"; !strings.Contains(body, want) {
		t.Errorf("options not applied, missing %q\n---\n%s", want, body)
	}
}
