package raiou_test

import (
	"testing"

	"github.com/Hayao0819/Kamisato/pkg/raiou"
)

func TestParsePkginfoString(t *testing.T) {
	const data = `# Generated by makepkg
pkgname = hello
pkgbase = hello
pkgver = 1.0.0-1
pkgdesc = A test package
url = https://example.com
arch = x86_64
size = 12345
builddate = 1700000000
license = MIT
depend = glibc
depend = gcc-libs
xdata = pkgtype=pkg
`

	p, err := raiou.ParsePkginfoString(data)
	if err != nil {
		t.Fatalf("ParsePkginfoString failed: %v", err)
	}

	if p.PkgName != "hello" {
		t.Errorf("PkgName = %q, want hello", p.PkgName)
	}
	if p.PkgVer != "1.0.0-1" {
		t.Errorf("PkgVer = %q, want 1.0.0-1", p.PkgVer)
	}
	if p.Arch != "x86_64" {
		t.Errorf("Arch = %q, want x86_64", p.Arch)
	}
	if p.Size != 12345 {
		t.Errorf("Size = %d, want 12345", p.Size)
	}
	if len(p.Depend) != 2 {
		t.Errorf("Depend len = %d, want 2", len(p.Depend))
	}
	if p.PkgType != "pkg" {
		t.Errorf("PkgType = %q, want pkg", p.PkgType)
	}
}

func TestParsePkginfoString_PkgTypeOptional(t *testing.T) {
	const data = `pkgname = hello
pkgver = 1.0.0-1
arch = x86_64
`
	p, err := raiou.ParsePkginfoString(data)
	if err != nil {
		t.Fatalf("pkgtype is optional; want success, got %v", err)
	}
	if p.PkgType != "" {
		t.Errorf("PkgType = %q, want empty", p.PkgType)
	}
}

func TestParsePkginfoString_EmptyValueTolerated(t *testing.T) {
	// "pkgdesc =" with an empty value must parse (repo-add tolerates it), leaving
	// the field empty rather than erroring.
	data := "pkgname = hello\npkgver = 1.0.0-1\npkgdesc =\narch = x86_64\n"
	p, err := raiou.ParsePkginfoString(data)
	if err != nil {
		t.Fatalf("empty value should be tolerated, got %v", err)
	}
	if p.PkgDesc != "" {
		t.Errorf("PkgDesc = %q, want empty", p.PkgDesc)
	}
	if p.PkgName != "hello" {
		t.Errorf("PkgName = %q, want hello", p.PkgName)
	}
}

func TestParseSrcinfoString(t *testing.T) {
	const data = "pkgbase = foo\n" +
		"\tpkgver = 1.2.3\n" +
		"\tpkgrel = 2\n" +
		"\tepoch = 1\n" +
		"\tarch = x86_64\n" +
		"\n" +
		"pkgname = foo\n" +
		"\n" +
		"pkgname = foo-libs\n"

	s, err := raiou.ParseSrcinfoString(data)
	if err != nil {
		t.Fatalf("ParseSrcinfoString failed: %v", err)
	}
	if s.PkgBase != "foo" {
		t.Errorf("PkgBase = %q, want foo", s.PkgBase)
	}
	if s.PkgVer != "1.2.3" {
		t.Errorf("PkgVer = %q, want 1.2.3", s.PkgVer)
	}
	if s.PkgRel != "2" {
		t.Errorf("PkgRel = %q, want 2", s.PkgRel)
	}
	if len(s.Packages) != 2 {
		t.Fatalf("Packages len = %d, want 2", len(s.Packages))
	}
	if s.Packages[0].PkgName != "foo" || s.Packages[1].PkgName != "foo-libs" {
		t.Errorf("Packages names = [%q %q], want [foo foo-libs]", s.Packages[0].PkgName, s.Packages[1].PkgName)
	}
}

func TestParseDescString(t *testing.T) {
	const data = `%FILENAME%
hello-1.0.0-1-x86_64.pkg.tar.zst

%NAME%
hello

%BASE%
hello

%VERSION%
1.0.0-1

%ARCH%
x86_64

%BUILDDATE%
1700000000

%DEPENDS%
glibc
gcc-libs
`

	d, err := raiou.ParseDescString(data)
	if err != nil {
		t.Fatalf("ParseDescString failed: %v", err)
	}
	if d.Name != "hello" {
		t.Errorf("Name = %q, want hello", d.Name)
	}
	if d.Version != "1.0.0-1" {
		t.Errorf("Version = %q, want 1.0.0-1", d.Version)
	}
	if len(d.Depends) != 2 {
		t.Errorf("Depends len = %d, want 2", len(d.Depends))
	}
	if len(d.ExtraFields) != 0 {
		t.Errorf("ExtraFields should be empty, got %v", d.ExtraFields)
	}
}

func TestDescToPKGINFO(t *testing.T) {
	const data = `%NAME%
hello

%BASE%
hello

%VERSION%
1.0.0-1

%ARCH%
x86_64

%DEPENDS%
glibc
`

	d, err := raiou.ParseDescString(data)
	if err != nil {
		t.Fatalf("ParseDescString failed: %v", err)
	}
	p, err := d.ToPKGINFO()
	if err != nil {
		t.Fatalf("ToPKGINFO failed: %v", err)
	}
	if p.PkgName != "hello" {
		t.Errorf("PkgName = %q, want hello", p.PkgName)
	}
	if p.PkgVer != "1.0.0-1" {
		t.Errorf("PkgVer = %q, want 1.0.0-1", p.PkgVer)
	}
	if len(p.Depend) != 1 || p.Depend[0] != "glibc" {
		t.Errorf("Depend = %v, want [glibc]", p.Depend)
	}
}

func TestDescToPKGINFO_Size(t *testing.T) {
	// A sync/repo db stores installed size as %ISIZE% (no %SIZE%); ToPKGINFO must
	// still surface it as PKGINFO.Size.
	sync := "%NAME%\nhello\n\n%VERSION%\n1.0.0-1\n\n%CSIZE%\n4096\n\n%ISIZE%\n12345\n"
	d, err := raiou.ParseDescString(sync)
	if err != nil {
		t.Fatalf("ParseDescString(sync): %v", err)
	}
	if p, err := d.ToPKGINFO(); err != nil {
		t.Fatalf("ToPKGINFO(sync): %v", err)
	} else if p.Size != 12345 {
		t.Errorf("sync db Size = %d, want 12345 (from %%ISIZE%%)", p.Size)
	}

	// A local db uses %SIZE% for the same installed size.
	local := "%NAME%\nhello\n\n%VERSION%\n1.0.0-1\n\n%SIZE%\n999\n"
	if d, err = raiou.ParseDescString(local); err != nil {
		t.Fatalf("ParseDescString(local): %v", err)
	}
	if p, err := d.ToPKGINFO(); err != nil {
		t.Fatalf("ToPKGINFO(local): %v", err)
	} else if p.Size != 999 {
		t.Errorf("local db Size = %d, want 999 (from %%SIZE%%)", p.Size)
	}
}
