package raiou_test

import (
	"strings"
	"testing"

	"github.com/Hayao0819/Kamisato/pkg/raiou"
)

func TestParsePkginfoString(t *testing.T) {
	const data = `# Generated by makepkg
pkgname = hello
pkgbase = hello
pkgver = 1.0.0-1
pkgdesc = A test package
url = https://example.com
arch = x86_64
size = 12345
builddate = 1700000000
license = MIT
depend = glibc
depend = gcc-libs
xdata = pkgtype=pkg
`

	p, err := raiou.ParsePkginfoString(data)
	if err != nil {
		t.Fatalf("ParsePkginfoString failed: %v", err)
	}

	if p.PkgName != "hello" {
		t.Errorf("PkgName = %q, want hello", p.PkgName)
	}
	if p.PkgVer != "1.0.0-1" {
		t.Errorf("PkgVer = %q, want 1.0.0-1", p.PkgVer)
	}
	if p.Arch != "x86_64" {
		t.Errorf("Arch = %q, want x86_64", p.Arch)
	}
	if p.Size != 12345 {
		t.Errorf("Size = %d, want 12345", p.Size)
	}
	if len(p.Depend) != 2 {
		t.Errorf("Depend len = %d, want 2", len(p.Depend))
	}
	if p.PkgType != "pkg" {
		t.Errorf("PkgType = %q, want pkg", p.PkgType)
	}
}

func TestParsePkginfoString_PkgTypeOptional(t *testing.T) {
	const data = `pkgname = hello
pkgver = 1.0.0-1
arch = x86_64
`
	p, err := raiou.ParsePkginfoString(data)
	if err != nil {
		t.Fatalf("pkgtype is optional; want success, got %v", err)
	}
	if p.PkgType != "" {
		t.Errorf("PkgType = %q, want empty", p.PkgType)
	}
}

func TestParsePkginfoString_EmptyValueTolerated(t *testing.T) {
	// "pkgdesc =" with an empty value must parse (repo-add tolerates it), leaving
	// the field empty rather than erroring.
	data := "pkgname = hello\npkgver = 1.0.0-1\npkgdesc =\narch = x86_64\n"
	p, err := raiou.ParsePkginfoString(data)
	if err != nil {
		t.Fatalf("empty value should be tolerated, got %v", err)
	}
	if p.PkgDesc != "" {
		t.Errorf("PkgDesc = %q, want empty", p.PkgDesc)
	}
	if p.PkgName != "hello" {
		t.Errorf("PkgName = %q, want hello", p.PkgName)
	}
}

func TestParseBuildinfoString(t *testing.T) {
	const data = `format = 2
pkgname = hello
pkgbase = hello
pkgver = 1.0.0-1
pkgarch = x86_64
pkgbuild_sha256sum = 0000000000000000000000000000000000000000000000000000000000000000
packager = Tester <t@example.com>
builddate = 1700000000
builddir = /build
startdir = /startdir
buildtool = devtools
buildtoolver = 1.0
buildenv = color
options = strip
installed = glibc-2.0-1-x86_64
`

	b, err := raiou.ParseBuildinfoString(data)
	if err != nil {
		t.Fatalf("ParseBuildinfoString failed: %v", err)
	}
	if b.Format != 2 {
		t.Errorf("Format = %d, want 2", b.Format)
	}
	if b.PkgName != "hello" {
		t.Errorf("PkgName = %q, want hello", b.PkgName)
	}
	if len(b.Installed) != 1 {
		t.Errorf("Installed len = %d, want 1", len(b.Installed))
	}
}

func TestParseBuildinfoString_UnsupportedFormat(t *testing.T) {
	const data = `format = 1
pkgname = hello
`
	if _, err := raiou.ParseBuildinfoString(data); err == nil {
		t.Fatal("expected error for unsupported format, got nil")
	}
}

func TestParseSrcinfoString(t *testing.T) {
	const data = "pkgbase = foo\n" +
		"\tpkgver = 1.2.3\n" +
		"\tpkgrel = 2\n" +
		"\tepoch = 1\n" +
		"\tarch = x86_64\n" +
		"\n" +
		"pkgname = foo\n" +
		"\n" +
		"pkgname = foo-libs\n"

	s, err := raiou.ParseSrcinfoString(data)
	if err != nil {
		t.Fatalf("ParseSrcinfoString failed: %v", err)
	}
	if s.PkgBase != "foo" {
		t.Errorf("PkgBase = %q, want foo", s.PkgBase)
	}
	if s.PkgVer != "1.2.3" {
		t.Errorf("PkgVer = %q, want 1.2.3", s.PkgVer)
	}
	if s.PkgRel != "2" {
		t.Errorf("PkgRel = %q, want 2", s.PkgRel)
	}
	if len(s.Packages) != 2 {
		t.Fatalf("Packages len = %d, want 2", len(s.Packages))
	}
	if s.Packages[0].PkgName != "foo" || s.Packages[1].PkgName != "foo-libs" {
		t.Errorf("Packages names = [%q %q], want [foo foo-libs]", s.Packages[0].PkgName, s.Packages[1].PkgName)
	}
}

func TestParseDescString(t *testing.T) {
	const data = `%FILENAME%
hello-1.0.0-1-x86_64.pkg.tar.zst

%NAME%
hello

%BASE%
hello

%VERSION%
1.0.0-1

%ARCH%
x86_64

%BUILDDATE%
1700000000

%DEPENDS%
glibc
gcc-libs
`

	d, err := raiou.ParseDescString(data)
	if err != nil {
		t.Fatalf("ParseDescString failed: %v", err)
	}
	if d.Name != "hello" {
		t.Errorf("Name = %q, want hello", d.Name)
	}
	if d.Version != "1.0.0-1" {
		t.Errorf("Version = %q, want 1.0.0-1", d.Version)
	}
	if len(d.Depends) != 2 {
		t.Errorf("Depends len = %d, want 2", len(d.Depends))
	}
	if len(d.ExtraFields) != 0 {
		t.Errorf("ExtraFields should be empty, got %v", d.ExtraFields)
	}
}

func TestDescToPKGINFO(t *testing.T) {
	const data = `%NAME%
hello

%BASE%
hello

%VERSION%
1.0.0-1

%ARCH%
x86_64

%DEPENDS%
glibc
`

	d, err := raiou.ParseDescString(data)
	if err != nil {
		t.Fatalf("ParseDescString failed: %v", err)
	}
	p, err := d.ToPKGINFO()
	if err != nil {
		t.Fatalf("ToPKGINFO failed: %v", err)
	}
	if p.PkgName != "hello" {
		t.Errorf("PkgName = %q, want hello", p.PkgName)
	}
	if p.PkgVer != "1.0.0-1" {
		t.Errorf("PkgVer = %q, want 1.0.0-1", p.PkgVer)
	}
	if len(p.Depend) != 1 || p.Depend[0] != "glibc" {
		t.Errorf("Depend = %v, want [glibc]", p.Depend)
	}
}

func TestDetectType(t *testing.T) {
	tests := []struct {
		name string
		data string
		want raiou.FileType
	}{
		{"buildinfo by format", "format = 2\npkgname = x\n", raiou.TypeBUILDINFO},
		{"buildinfo by key", "builddir = /build\npkgname = x\n", raiou.TypeBUILDINFO},
		{"srcinfo by key", "pkgbase = x\nsource = https://example.com/x.tar\n", raiou.TypeSRCINFO},
		{"pkginfo default", "pkgname = x\npkgver = 1.0\n", raiou.TypePKGINFO},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := raiou.DetectType(strings.NewReader(tt.data))
			if err != nil {
				t.Fatalf("DetectType failed: %v", err)
			}
			if got != tt.want {
				t.Errorf("DetectType = %v, want %v", got, tt.want)
			}
		})
	}
}
