name: Lint Dockerfile

on: 
  push:
      paths:
        - 'Dockerfile'
  pull_request:
      paths:
        - 'Dockerfile'
  workflow_dispatch:

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v7

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.3.0
        with:
          dockerfile: "Dockerfile"
