name: Go Lint & Vet

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  vet:
    name: Run go vet
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Prepare dummy web
        run: mkdir -p lumine/embed/out && touch lumine/embed/out/index.html

      - name: Run go vet
        run: go vet ./...

  staticcheck:
    name: Run staticcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Prepare dummy web
        run: mkdir -p lumine/embed/out && touch lumine/embed/out/index.html

      - name: Run staticcheck
        run: $(go env GOPATH)/bin/staticcheck ./...

  golangci-lint:
    name: Run golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
          args: ./...
